Repository frenck/python-vehicle, pull requests merged in 2021-12, with the labels that each got.

#28 Fix station wagon vehicle interior value
  src/vehicle/const.py
Labels: bugfix

#29 Added "pick-up truck" to vehicle interior types
  src/vehicle/const.py
Labels: enhancement

#30 Added support for requesting motorcycles, mopeds/scooters
  src/vehicle/models.py
Labels: new-feature

#41 Fixed incorrect closed interior constant value
  src/vehicle/const.py
Labels: bugfix
