Repository frenck/python-vehicle, pull requests merged in 2023-10, with the labels that each got.

#518 Add Python 3.12, Drop Python 3.10
  .github/labels.yml
  .github/workflows/linting.yaml
  .github/workflows/release.yaml
  .github/workflows/tests.yaml
  .github/workflows/typing.yaml
  README.md
  poetry.lock
  pyproject.toml
  sonar-project.properties
  src/vehicle/rdw.py
  tests/test_info.py
Labels: breaking-change

#416 Fix missing fields on new car
  src/vehicle/models.py
  tests/fixtures/VXJ99N.json
  tests/test_info.py
Labels: bugfix

#450 Use syrupy for dict assertions
  poetry.lock
  pyproject.toml
  tests/__snapshots__/test_info.ambr
  tests/test_info.py
Labels: enhancement
