Repository frenck/python-vehicle, pull requests merged in 2023-05, with the labels that each got.

#378 Fix typo
  src/vehicle/models.py
Labels: documentation

#379 Fix contributing guidlines link
  README.md
Labels: documentation

#383 Fix string formatting issue
  src/vehicle/rdw.py
  tests/test_info.py
  tests/test_rdw.py
Labels: bugfix

#391 Ignore .venv folder for YAMLlint
  .yamllint
Labels: ci

#392 Remove duplicate lint
  .github/workflows/linting.yaml
Labels: ci
